apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  storageClassName: manual
  volumeName: immich-library-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 9Ti
