apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
spec:
  type: LoadBalancer
  ports:
  - port: 51821
    targetPort: 51821
    protocol: UDP
  selector:
    name: wireguard
